/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './sanity/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 palette (from the Stitch design tokens)
        primary: '#004873',
        'primary-container': '#1e6091',
        'on-primary': '#ffffff',
        'on-primary-container': '#b5d9ff',
        'primary-fixed': '#cee5ff',
        'primary-fixed-dim': '#97cbff',
        'on-primary-fixed': '#001d33',
        'on-primary-fixed-variant': '#004a77',
        secondary: '#3b6185',
        'secondary-container': '#afd5ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#365d80',
        'secondary-fixed': '#cfe5ff',
        'secondary-fixed-dim': '#a4caf3',
        'on-secondary-fixed': '#001d34',
        'on-secondary-fixed-variant': '#21496c',
        tertiary: '#5a4000',
        'tertiary-container': '#785600',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffcd6b',
        'tertiary-fixed': '#ffdea4',
        'tertiary-fixed-dim': '#f0bf5c',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4200',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#216293',
        'on-surface': '#191c1d',
        'on-surface-variant': '#41474f',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        outline: '#717880',
        'outline-variant': '#c1c7d0',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#97cbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // Brand accents (consistent across the mockups)
        'brand-navy': '#00020e',
        'brand-gold': '#C89B3C',
        'deep-navy': '#0D1B3E',
        'navy-deep': '#0D1B3E',
        'gold-accent': '#C89B3C',
        'cta-gold': '#C89B3C',
      },
      fontFamily: {
        heading: ['var(--font-domine)', 'Domine', 'serif'],
        body: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        // Stitch font-family utilities
        'display-lg': ['var(--font-domine)', 'Domine', 'serif'],
        'headline-xl': ['var(--font-domine)', 'Domine', 'serif'],
        'headline-lg': ['var(--font-domine)', 'Domine', 'serif'],
        'headline-md': ['var(--font-domine)', 'Domine', 'serif'],
        'headline-lg-mobile': ['var(--font-domine)', 'Domine', 'serif'],
        'body-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'body-md': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'label-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'label-sm': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
      },
      fontSize: {
        // Fluid headline scale — clamps between a mobile-safe min and the original desktop size.
        // Relative line-heights keep proportions correct as the font size scales.
        'display-lg': ['clamp(2.25rem, 1.4rem + 4.25vw, 4rem)', { lineHeight: '1.08', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['clamp(1.875rem, 1.3rem + 2.875vw, 3rem)', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['clamp(1.5625rem, 1.35rem + 1.1vw, 2rem)', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['clamp(1.25rem, 1.13rem + 0.6vw, 1.5rem)', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      spacing: {
        'section-gap': '100px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'max-width': '1280px',
        'container-max': '1280px',
        unit: '8px',
        'stack-lg': '32px',
        'stack-md': '16px',
      },
      maxWidth: {
        container: '1280px',
        'max-width': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.7s ease-out forwards',
      },
    },
  },
  plugins: [],
}
